services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ./Backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/my-project
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
